language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - jruby-head
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
services:
  - rabbitmq
matrix:
  allow_failures:
    - rvm: jruby-head
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 1.9.3
      jdk: oraclejdk7
